title: "Ääzebär"
subtitle: "TODO SUBTITLE"
description: "TODO DESCRIPTION"
og_image: /assets/images/ab-logo_w.jpg # image used when sharing links. Can be a logo or portait. ATTENTION: also check og_image when updating!

url: "https://peabear.github.io" # ATTENTION: Also check social-links when changing!
baseurl: "/homepage" # ATTENTION: check links within this config (e.g. in footer) when changing!

minimal_mistakes_skin: "aqua" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
encoding: utf-8 # no official jekyll standard, but: might help and will not break anything


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
locale: de-DE # important: - instead of _
date_format: "%d.%m.%Y" # german date format - using numbers for months since german names do not work
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-feed # Creates an Atom/RSS feed (usually at /feed.xml) for subscribers
  - jekyll-include-cache # Speeds up the build process by caching repetitive includes
  - jekyll-last-modified-at # Automatically syncs create and update timestamps with your Git commit history; important for automatic sitemap and feed generation
  - jekyll-paginate # Enables pagination for long lists of blog posts
  - jekyll-sitemap # Automatically generates a sitemap.xml for search engines
  - jemoji # Supports GitHub-style emojis like :books: or :rocket:

include:
  - _pages

# the following files are not available via the website
exclude:
  - README.md
  - CNAME
  - LICENSE
  - scripts/
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - exclude/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true # alculates the estimated reading time (e.g., "3 min read") and displays it at the top of the article.
      show_date: true # show creation date
      comments: false # Activates the comment section below the post. You must also configure a provider _config.yml.
      share: false # Displays social media buttons (Twitter, Facebook, LinkedIn, etc.), allowing readers to share your post with a single click.
      related: false # Enables the "You May Also Enjoy" section. Displays similar posts here (based on shared tags or categories).
      author_profile: true
      header:
        teaser: "/assets/images/ab-logo_w.jpg"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# site properties
email: peabear@web.de # ATTENTION: Also check mail adress in author-info when changing!

author:
  name: "Ääzebär e.V. Lohmar"
  bio    : "TODO Bio"
  avatar: /assets/images/ab-logo_w.jpg # Path to photo. ATTENTION: also check og_image when updating!
  location: "Lohmar, Germany"
  links:
    - label: Email
      icon: "fas fa-square-envelope"
      url: "mailto:peabear@web.de" # ATTENTION: Also check mail adress in site properties when changing!
    - label: Facebook TODO-LINK
      icon: "fab fa-fw fa-facebook"
      url: "TODO" # ATTENTION: Also check social-links when changing!

atom_feed: 
  hide: true # not rendered anyway as long as search is active. So I put RSS feed to footer explicitly

footer:
  extra_footer_content: '© 2008 - 2026 Ääzebär e.V. Lohmar &#124; <a href="/homepage/feed.xml"><i class="fas fa-square-rss" style="color: #ee802f;"></i> RSS Feed</a> &#124; <a href="/homepage/legal/"><i class="fas fa-scale-balanced"></i> Impressum und Datenschutzerklärung</a>'
